### PR TITLE
Clarify what the redirect URL for Discord should be

### PR DESCRIPTION
**Pull request by mja00**
I knew a URL would need to be set but didn't know what it would need to be until the request was made. This'll clarify for people beforehand to set the URL properly. Feel free to move the line around or put it elsewhere.

### CODE REVIEW

**Comment by Erisa** [comment]
Thanks! Yeah its the same thing you put in config.json, I remember I wanted to put this in the readme but forgot. I'll look at this in a bit when I'm free

**Comment by mja00** [comment]
I didn't even notice it was that same URL. My brain is absolutely fried lol

**Comment by Erisa** [comment]
I ended up fixing this in https://github.com/Erisa/discord-oidc-worker/commit/d954e71a5b9a1df5d5cfc9d1bf788dd74860f31a by introducing a requirements section and then specifying they're the same further down. Thought it was getting too clunky to have the requirements as a single point at the top.

Thanks again!

**Comment by mja00** [comment]
Fair point. Thanks for adding it!

**Pull request closed without merging**
